# Generated by Django 4.1.7 on 2023-07-07 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wx', '0011_wxuser_name_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=255, verbose_name='人物名称')),
                ('voice_id', models.CharField(max_length=50, verbose_name='voice_id')),
                ('class_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='类型')),
                ('adapt_scense', models.CharField(blank=True, max_length=255, null=True, verbose_name='适用场景')),
                ('adapt_language', models.CharField(blank=True, max_length=255, null=True, verbose_name='适用语言')),
                ('is_adatpt_er', models.BooleanField(default=False, verbose_name='是否适用儿话音')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '语音(平台)',
                'verbose_name_plural': '语音(平台)',
                'db_table': 'z_voice_type',
            },
        ),
        migrations.CreateModel(
            name='VoiceTypeUserCustomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('voice_id', models.CharField(max_length=50, verbose_name='voice_id')),
                ('wx_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_custom_voice', to='wx.wxuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '语音(用户自定义)',
                'verbose_name_plural': '语音(用户自定义)',
                'db_table': 'z_voice_type_user_custom',
            },
        ),
        migrations.CreateModel(
            name='VoiceCreateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('voice_id', models.CharField(max_length=50, verbose_name='voice_id')),
                ('text', models.TextField(blank=True, null=True, verbose_name='文本')),
                ('voice_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='语音url')),
                ('wx_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_record_voice', to='wx.wxuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '语音创建记录',
                'verbose_name_plural': '语音创建记录',
                'db_table': 'z_voice_create_record',
            },
        ),
    ]
