# Generated by Django 4.1.7 on 2023-07-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicecreaterecord',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='是否个性化'),
        ),
    ]
