# Generated by Django 4.1.7 on 2023-07-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice", "0002_voicecreaterecord_is_custom"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicetypemodel",
            name="example_voice",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="示例语音"
            ),
        ),
    ]
