# Generated by Django 4.1.7 on 2023-07-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0003_voicetypemodel_example_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicecreaterecord',
            name='speech_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='语速'),
        ),
    ]
