# Generated by Django 4.1.7 on 2023-07-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0004_voicecreaterecord_speech_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicetypemodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='voice/avatar', verbose_name='头像'),
        ),
    ]
